# Makefile 
# Jadon/Saraah/Yusuf/Tahir

SRCDIR = src
BINDIR = bin
DOCDIR = doc
TESTDIR = test

JUNIT = ./gson/gson-2.6.2.jar -sourcepath ./src ./src/$*.java


JAVAC = javac
JFLAGS = -g -d $(BINDIR) -cp $(BINDIR)

#to check the src and test folders for the .java files
#also to ensure that class files are in bin 
vpath %.java $(SRCDIR):$(TESTDIR)
vpath %.class $(BINDIR)

.SUFFIXES: .java .class

.java.class:
	$(JAVAC) $(JFLAGS) $<

classes: Menu.class Database.class UberEatsMobileApp.class UberEatsRestaurantApp.class Restaurant.class PlacedOrders.class
#  Passenger.class \
		# UberApp.class Ride.class UberRide.class Database.class

default: $(CLASSES)

doc:
	javadoc -d $(DOCDIR) -cp $(DOCDIR) $(SRCDIR)/*.java

test_classes: Menu.class Database.class UberEatsMobileApp.class UberEatsRestaurantApp.class Restaurant.class PlacedOrders.class
			# UberApp.class Ride.class UberRide.class Database.class



junit: test_classes
Menu.class: Menu.java
	javac -d $(BINDIR) -cp $(JUNIT)
UberEatsMobileApp.class: UberEatsMobileApp.java
	javac -d $(BINDIR) -cp $(JUNIT)
Database.class: Database.java
	javac -d $(BINDIR) -cp $(JUNIT)
UberEatsRestaurantApp.class: UberEatsRestaurantApp.java
	javac -d $(BINDIR) -cp $(JUNIT)
Restaurant.class: Restaurant.java
	javac -d $(BINDIR) -cp $(JUNIT)
PlacedOrders.class: PlacedOrders.java
	javac -d $(BINDIR) -cp $(JUNIT)

	
# Passenger.class: Passenger.java
# 	javac -d $(BINDIR) -cp $(JUNIT)
# UberApp.class: UberApp.java
# 	javac -d $(BINDIR) -cp $(JUNIT)
# Ride.class: Ride.java
# 	javac -d $(BINDIR) -cp $(JUNIT)
# UberRide.class: UberRide.java
# 	javac -d $(BINDIR) -cp $(JUNIT)
# Database.class: Database.java
# 	javac -d $(BINDIR) -cp $(JUNIT)


#test_classes: SearchItLinearTest.java eDirectoryTest.java #SearchItTest.java PrintItTest.java
	      
#junit: test_classes
#	javac -d $(BINDIR) -cp ../junit/junit-4.12.jar -sourcepath ./src $*.java
#	#java -cp $(BINDIR):$(JUNIT) org.junit.runner.JUnitCore $*.java	

clean:
	rm -f  $(BINDIR)/*.class
	rm -Rf doc